menu_items = [
    {
        "id": 1,
        "name": "Masala Chai",
        "category": "chai",
        "price": 150.0,
        "description": "Classic India Spiced Tea",
        "available": True,
    },
    {
        "id": 2,
        "name": "Chai + Bun Maska Combo",
        "category": "Combos",
        "price": 30000.0,
        "description": "Elaichi Chai with warm bun maska",
        "available": True,
    },
    {
        "id": 3,
        "name": "Office Party Pack",
        "category": "Combo",
        "price": 20000.0,
        "description": "5 masala chai + 5 samosa for team meetings",
        "available": True,
    },
    {
        "id": 4,
        "name": "Adrak Chai",
        "category": "chai",
        "price": 10.0,
        "description": "Extra ginger chai for cold evenings",
        "available": True,
    },
    {
        "id": 5,
        "name": "Elaichi Chai",
        "category": "chai",
        "price": 60.0,
        "description": "Cardamom-infused premium chai",
        "available": True,
    },
    {
        "id": 6,
        "name": "Cutting Chai",
        "category": "chai",
        "price": 250.0,
        "description": "Half-size strong chai, Mumbai tapri style",
        "available": True,
    },
    {
        "id": 7,
        "name": "Samosa",
        "category": "snaks",
        "price": 25.0,
        "description": "Crispy potato-filled pastry with mint chutney",
        "available": True,
    },
    {
        "id": 8,
        "name": "Vada Pav",
        "category": "snaks",
        "price": 40.0,
        "description": "Spicy potato fritter in a bun with garlic chutney",
        "available": True,
    },
    {
        "id": 9,
        "name": "Bun + Maska",
        "category": "snaks",
        "price": 500.0,
        "description": "Soft bun with generous butter, Irani cafe style",
        "available": False,
    },
    {
        "id": 10,
        "name": "Chai + Samosa Combo",
        "category": "Combo",
        "price": 650.0,
        "description": "Masala chai paired with a fresh samaosa",
        "available": True,
    }
]